/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesPrintingRouteImport } from './routes/services.printing'
import { Route as ServicesPassportPhotosRouteImport } from './routes/services.passport-photos'
import { Route as ServicesNtsaRouteImport } from './routes/services.ntsa'
import { Route as ServicesKraRouteImport } from './routes/services.kra'
import { Route as ServicesCvWritingRouteImport } from './routes/services.cv-writing'
import { Route as ServicesComputerRepairRouteImport } from './routes/services.computer-repair'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPrintingRoute = ServicesPrintingRouteImport.update({
  id: '/printing',
  path: '/printing',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesPassportPhotosRoute = ServicesPassportPhotosRouteImport.update({
  id: '/passport-photos',
  path: '/passport-photos',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesNtsaRoute = ServicesNtsaRouteImport.update({
  id: '/ntsa',
  path: '/ntsa',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesKraRoute = ServicesKraRouteImport.update({
  id: '/kra',
  path: '/kra',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCvWritingRoute = ServicesCvWritingRouteImport.update({
  id: '/cv-writing',
  path: '/cv-writing',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesComputerRepairRoute = ServicesComputerRepairRouteImport.update({
  id: '/computer-repair',
  path: '/computer-repair',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/computer-repair': typeof ServicesComputerRepairRoute
  '/services/cv-writing': typeof ServicesCvWritingRoute
  '/services/kra': typeof ServicesKraRoute
  '/services/ntsa': typeof ServicesNtsaRoute
  '/services/passport-photos': typeof ServicesPassportPhotosRoute
  '/services/printing': typeof ServicesPrintingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/computer-repair': typeof ServicesComputerRepairRoute
  '/services/cv-writing': typeof ServicesCvWritingRoute
  '/services/kra': typeof ServicesKraRoute
  '/services/ntsa': typeof ServicesNtsaRoute
  '/services/passport-photos': typeof ServicesPassportPhotosRoute
  '/services/printing': typeof ServicesPrintingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/computer-repair': typeof ServicesComputerRepairRoute
  '/services/cv-writing': typeof ServicesCvWritingRoute
  '/services/kra': typeof ServicesKraRoute
  '/services/ntsa': typeof ServicesNtsaRoute
  '/services/passport-photos': typeof ServicesPassportPhotosRoute
  '/services/printing': typeof ServicesPrintingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/services/computer-repair'
    | '/services/cv-writing'
    | '/services/kra'
    | '/services/ntsa'
    | '/services/passport-photos'
    | '/services/printing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/services/computer-repair'
    | '/services/cv-writing'
    | '/services/kra'
    | '/services/ntsa'
    | '/services/passport-photos'
    | '/services/printing'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/services/computer-repair'
    | '/services/cv-writing'
    | '/services/kra'
    | '/services/ntsa'
    | '/services/passport-photos'
    | '/services/printing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/printing': {
      id: '/services/printing'
      path: '/printing'
      fullPath: '/services/printing'
      preLoaderRoute: typeof ServicesPrintingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/passport-photos': {
      id: '/services/passport-photos'
      path: '/passport-photos'
      fullPath: '/services/passport-photos'
      preLoaderRoute: typeof ServicesPassportPhotosRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ntsa': {
      id: '/services/ntsa'
      path: '/ntsa'
      fullPath: '/services/ntsa'
      preLoaderRoute: typeof ServicesNtsaRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/kra': {
      id: '/services/kra'
      path: '/kra'
      fullPath: '/services/kra'
      preLoaderRoute: typeof ServicesKraRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/cv-writing': {
      id: '/services/cv-writing'
      path: '/cv-writing'
      fullPath: '/services/cv-writing'
      preLoaderRoute: typeof ServicesCvWritingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/computer-repair': {
      id: '/services/computer-repair'
      path: '/computer-repair'
      fullPath: '/services/computer-repair'
      preLoaderRoute: typeof ServicesComputerRepairRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesComputerRepairRoute: typeof ServicesComputerRepairRoute
  ServicesCvWritingRoute: typeof ServicesCvWritingRoute
  ServicesKraRoute: typeof ServicesKraRoute
  ServicesNtsaRoute: typeof ServicesNtsaRoute
  ServicesPassportPhotosRoute: typeof ServicesPassportPhotosRoute
  ServicesPrintingRoute: typeof ServicesPrintingRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesComputerRepairRoute: ServicesComputerRepairRoute,
  ServicesCvWritingRoute: ServicesCvWritingRoute,
  ServicesKraRoute: ServicesKraRoute,
  ServicesNtsaRoute: ServicesNtsaRoute,
  ServicesPassportPhotosRoute: ServicesPassportPhotosRoute,
  ServicesPrintingRoute: ServicesPrintingRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
